### ISSUE TITLE
Wizard Portal teleport to SkyWars

### ISSUE THREAD

**Issue by doej1367** [Cobble8/SkyblockPersonalized#9]
The fact that I get teleported to SkyWars when I enter the Wizard Portal, is that some easter egg from this mod? If so how can I deactivate it?

![grafik](https://user-images.githubusercontent.com/19228364/155311939-815432f2-d5af-4a76-beb3-bb18aca64ad8.png)

**Comment by KNDeVV** [comment]
Set `dwarven.garryTP.notifToggle` in config file to `false`

**Comment by doej1367** [comment]
> Set `dwarven.garryTP.notifToggle` in config file to `false`

Thx, that did the trick. Now I can see the Wizards message again.

![grafik](https://user-images.githubusercontent.com/19228364/163063588-4bf18135-2da3-4271-bccd-e1d9eb5b3549.png)
